disabled_rules:
  - trailing_comma
  - opening_brace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping

excluded:
  - .build
  - Pods
  - Carthage
  - "**/Tests/**"

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - c
    - d
    - e
    - id
    - x
    - y
    - url
    - vm

type_name:
  min_length: 3
  max_length: 60

force_unwrapping:
  severity: error
  excluded: "**/Tests/**"

large_tuple:
  warning: 3
  error: 5

analyzer_rules:
  - unused_import
  - unused_declaration
