disabled_rules:
  - trailing_comma
  - opening_brace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - orphaned_doc_comment
  - superfluous_disable_command

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - .build
  - Pods
  - Carthage
  - "**/Tests/**"
  - "**/Views/**"

identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - c
    - d
    - e
    - v
    - m
    - id
    - x
    - y
    - url
    - vm
    - db

type_name:
  min_length: 3
  max_length: 60

force_unwrapping:
  severity: warning

large_tuple:
  warning: 5
  error: 10

analyzer_rules:
  - unused_import
  - unused_declaration
