#!/usr/bin/env bash
# generate_secrets.sh
# Xcode Run Script Phase: reads .env at the repo root and emits
# apps/ios/SoloCompass/Config/GeneratedSecrets.swift as enum Secrets static constants.
#
# Usage (Xcode Pre-build Run Script Phase):
#   "${SRCROOT}/../../scripts/generate_secrets.sh"
#
# When invoked outside Xcode (CI / manual), the script falls back to
# script-relative path resolution so it Just Works.
#
# Input:  <repo-root>/.env
# Output: apps/ios/SoloCompass/Config/GeneratedSecrets.swift

set -euo pipefail

# Resolve repo root: prefer ${SRCROOT}/../.. (Xcode); fall back to script dir/.. .
if [[ -n "${SRCROOT:-}" && -f "${SRCROOT}/../../.env" ]]; then
    REPO_ROOT="$(cd "${SRCROOT}/../.." && pwd)"
elif [[ -n "${SRCROOT:-}" && -f "${SRCROOT}/.env" ]]; then
    REPO_ROOT="${SRCROOT}"
else
    REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

ENV_FILE="${REPO_ROOT}/.env"
OUTPUT_FILE="${REPO_ROOT}/apps/ios/SoloCompass/Config/GeneratedSecrets.swift"

emit_swift() {
    local key="$1" base="$2" model="$3" sb_url="$4" sb_key="$5" sentry="$6"
    mkdir -p "$(dirname "${OUTPUT_FILE}")"
    cat > "${OUTPUT_FILE}" << SWIFT
// GeneratedSecrets.swift — AUTO-GENERATED by scripts/generate_secrets.sh
// DO NOT EDIT MANUALLY. DO NOT COMMIT (see .gitignore).
// Regenerated on every build from the repo-root .env file.

enum Secrets {
    static let deepSeekApiKey: String = "${key}"
    static let deepSeekBaseURL: String = "${base}"
    static let deepSeekModel: String = "${model}"
    static let supabaseURL: String = "${sb_url}"
    static let supabaseAnonKey: String = "${sb_key}"
    static let sentryDSN: String = "${sentry}"
}
SWIFT
}

# If .env doesn't exist, emit empty placeholder so build proceeds.
if [[ ! -f "${ENV_FILE}" ]]; then
    if [[ -f "${OUTPUT_FILE}" ]] && grep -q 'deepSeekApiKey: String = "sk-' "${OUTPUT_FILE}"; then
        echo "[generate_secrets] .env not found, keeping existing ${OUTPUT_FILE}"
        exit 0
    fi
    echo "[generate_secrets] WARN: .env not found; emitting empty Secrets so build proceeds." >&2
    emit_swift "" "https://api.deepseek.com/v1" "deepseek-chat" "" "" ""
    echo "[generate_secrets] wrote placeholder ${OUTPUT_FILE}"
    exit 0
fi

# ── Helper ──────────────────────────────────────────────────────────────────
read_env_value() {
    local key="$1"
    local value=""
    value=$(grep -E "^${key}=" "${ENV_FILE}" | head -1 | cut -d'=' -f2- | tr -d '\r')
    # Escape backslash and double-quote for Swift string literal
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    echo "${value}"
}

# ── Read values ──────────────────────────────────────────────────────────────
DEEPSEEK_API_KEY=$(read_env_value "DEEPSEEK_API_KEY")
DEEPSEEK_BASE_URL=$(read_env_value "DEEPSEEK_BASE_URL")
DEEPSEEK_MODEL=$(read_env_value "DEEPSEEK_MODEL")
SUPABASE_URL=$(read_env_value "SUPABASE_URL")
SUPABASE_ANON_KEY=$(read_env_value "SUPABASE_ANON_KEY")
SENTRY_DSN=$(read_env_value "SENTRY_DSN")

# Defaults
[[ -z "${DEEPSEEK_BASE_URL}" ]] && DEEPSEEK_BASE_URL="https://api.deepseek.com/v1"
[[ -z "${DEEPSEEK_MODEL}"    ]] && DEEPSEEK_MODEL="deepseek-chat"

emit_swift "${DEEPSEEK_API_KEY}" "${DEEPSEEK_BASE_URL}" "${DEEPSEEK_MODEL}" "${SUPABASE_URL}" "${SUPABASE_ANON_KEY}" "${SENTRY_DSN}"
echo "[generate_secrets] wrote ${OUTPUT_FILE}"
